### ISSUE TITLE
When will it be integrated into the official client?

### ISSUE THREAD

**Issue by rugk** [nextcloud/gsoc_client#18]
GNOME 3.26 has been released and with Fedora 27 being released also many people now use it, however NextCloud still uses the status icons. This even causes the NextCloud window to be opened at each (auto)start, as it just cannot display an icon. (unless the topicons plus extension or so is installed)

So at least the "deep Nautilus integration" would be nice to see soon.

**Comment by mbevc1** [comment]
This also means there is no way after closing it to background to open GUI again - without killing and restarting it.

**Comment by juliusknorr** [comment]
I just created a pull request to the main client repo. Some minor fixes are left, that should be done tomorrow. See https://github.com/nextcloud/client/pull/55
